blank_issues_enabled: false
contact_links:
  - name: Bluetooth Proxy issue
    url: https://github.com/esphome/bluetooth-proxies/issues
    about: Please search for or create an issue in the bluetooth-proxies repository.
  - name: Voice Assistant issue
    url: https://github.com/esphome/wake-word-voice-assistant/issues
    about: Please search for or create an issue in the bluetooth-proxies repository.
  - name: Media Player issue
    url: https://github.com/esphome/media-players/issues
    about: Please search for or create an issue in the bluetooth-proxies repository.
