esphome:
  name: m5stack-atom-speaker-kit
  friendly_name: M5Stack Atom Speaker Kit
  min_version: 2024.6.0
  name_add_mac_suffix: true
  project:
    name: m5stack.atom-speaker-kit
    version: "24.7.4.1"

esp32:
  board: m5stack-atom
  framework:
    type: arduino

logger:
api:

ota:
  - platform: esphome
    id: ota_esphome
  - platform: http_request
    id: ota_http_request

update:
  - platform: http_request
    id: update_http_request
    name: Firmware
    source: https://firmware.esphome.io/media-player/m5stack-atom-speaker-kit/manifest.json

http_request:
  verify_ssl: false

dashboard_import:
  package_import_url: github://esphome/firmware/media-player/m5stack-atom-speaker-kit.yaml@main

wifi:
  ap:

captive_portal:

improv_serial:

i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO21
    i2s_bclk_pin: GPIO22

media_player:
  - platform: i2s_audio
    id: media_out
    name: None
    dac_type: external
    i2s_dout_pin: GPIO25
    mode: mono

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    id: top_button
    name: Button
    on_click:
      - media_player.toggle: media_out

light:
  - platform: fastled_clockless
    id: led
    name: None
    pin: GPIO27
    chipset: SK6812
    num_leds: 1
    rgb_order: grb

button:
  - platform: safe_mode
    id: button_safe_mode
    name: Safe Mode Boot

  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset
