esphome:
  name: raspiaudio-muse-proto
  friendly_name: RaspiAudio Muse Proto
  min_version: 2024.6.0
  name_add_mac_suffix: true
  project:
    name: raspiaudio.muse-proto
    version: "1.0"

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

logger:
api:

ota:
  - platform: esphome

dashboard_import:
  package_import_url: github://esphome/firmware/media-player/raspiaudio-muse-proto.yaml@main

wifi:
  ap:

captive_portal:

improv_serial:

i2s_audio:
  - i2s_lrclk_pin: GPIO25
    i2s_bclk_pin: GPIO5

microphone:
  - platform: i2s_audio
    id: board_microphone
    channel: left
    i2s_din_pin: GPIO35
    adc_type: external
    pdm: false

speaker:
  - platform: i2s_audio
    id: board_external_speakers
    dac_type: external
    i2s_dout_pin:
      number: GPIO26
      allow_other_uses: true
    mode: mono

media_player:
  - platform: i2s_audio
    id: media_out
    name: None
    dac_type: external
    i2s_dout_pin:
      number: GPIO26
      allow_other_uses: true
    mode: mono
    mute_pin:
      number: GPIO21
      inverted: true

voice_assistant:
  microphone: board_microphone
  speaker: board_external_speakers
  on_start:
    - light.turn_on:
        id: board_led
        blue: 100%
        red: 0%
        green: 0%
        effect: none
  on_tts_start:
    - light.turn_on:
        id: board_led
        blue: 60%
        red: 20%
        green: 20%
        effect: none
  on_tts_end:
    - light.turn_on:
        id: board_led
        blue: 60%
        red: 20%
        green: 20%
        effect: pulse
  on_end:
    - delay: 1s
    - wait_until:
        not:
          speaker.is_playing:
    - light.turn_off: board_led
  on_error:
    - light.turn_on:
        id: board_led
        blue: 0%
        red: 100%
        green: 0%
        effect: none
    - delay: 1s
    - light.turn_off: board_led

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
    name: Action
    on_multi_click:
      - timing:
          - ON FOR AT MOST 350ms
          - OFF FOR AT LEAST 10ms
        then:
          - media_player.toggle: media_out
      - timing:
          - ON FOR AT LEAST 350ms
        then:
          - voice_assistant.start:
      - timing:
          - ON FOR AT LEAST 350ms
          - OFF FOR AT LEAST 10ms
        then:
          - voice_assistant.stop:

light:
  - platform: esp32_rmt_led_strip
    id: board_led
    name: None
    disabled_by_default: true
    pin: GPIO22
    default_transition_length: 0s
    chipset: WS2812
    num_leds: 1
    rgb_order: grb
    rmt_channel: 0
    effects:
      - pulse:
          transition_length: 250ms
          update_interval: 250ms
