substitutions:
  name: "lilygo-ttgo-poe-bt-proxy"
  friendly_name: Bluetooth Proxy

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: true
  project:
    name: esphome.bluetooth-proxy
    version: "24.7.4.1"

esp32:
  # Platform.io does not have an explicit profile for the module.
  # We can treat it like a standard dev board based around a standard WROOM module.
  # See: https://github.com/Xinyuan-LilyGO/LilyGO-T-ETH-POE
  board: esp32dev
  framework:
    type: esp-idf

# See: https://esphome.io/components/ethernet.html#configuration-for-lilygo-ttgo-t-internet-poe-esp32-wroom-lan8270a-chip
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0

api:
logger:
ota:
  - platform: esphome
    id: ota_esphome
  - platform: http_request
    id: ota_http_request

update:
  - platform: http_request
    id: update_http_request
    name: Firmware
    source: https://firmware.esphome.io/bluetooth-proxy/lilygo-t-eth-poe/manifest.json

http_request:

dashboard_import:
  package_import_url: github://esphome/firmware/bluetooth-proxy/lilygo-t-eth-poe.yaml@main

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

button:
  - platform: safe_mode
    id: button_safe_mode
    name: Safe Mode Boot

  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset
