---
esphome:
  name: esp32-s3-box
  friendly_name: ESP32 S3 Box
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio
  project:
    name: esphome.voice-assistant
    version: "1.0"
  min_version: 2023.11.4

esp32:
  board: esp32s3box
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"

psram:
  mode: octal
  speed: 80MHz

external_components:
  - source: github://pr#5230
    components: esp_adf
    refresh: 0s

api:
  on_client_connected:
    then:
      - script.execute: reset_display
  on_client_disconnected:
    then:
      - script.execute: reset_display

ota:
logger:
  hardware_uart: USB_SERIAL_JTAG

dashboard_import:
  package_import_url: github://esphome/firmware/voice-assistant/esp32-s3-box.yaml@main

wifi:
  ap:
  on_connect:
    then:
      - script.execute: reset_display
      - delay: 5s # Gives time for improv results to be transmitted
      - ble.disable:
  on_disconnect:
    then:
      - script.execute: reset_display
      - ble.enable:

improv_serial:

esp32_improv:
  authorizer: none

button:
  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO1
      inverted: true
    name: "Mute"

  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: Top Left Button
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at least 250ms
          - OFF for at least 50ms
        then:
          - if:
              condition:
                switch.is_off: use_wake_word
              then:
                - if:
                    condition: voice_assistant.is_running
                    then:
                      - voice_assistant.stop:
                      - script.execute: reset_display
                    else:
                      - voice_assistant.start:
              else:
                - voice_assistant.stop
                - delay: 1s
                - script.execute: reset_display
                - script.wait: reset_display
                - voice_assistant.start_continuous:
      - timing:
          - ON for at least 10s
        then:
          - button.press: factory_reset_btn

output:
  - platform: ledc
    pin: GPIO45
    id: backlight_output

light:
  - platform: monochromatic
    id: led
    name: LCD Backlight
    output: backlight_output
    restore_mode: RESTORE_DEFAULT_ON
    default_transition_length: 250ms

esp_adf:

microphone:
  - platform: esp_adf
    id: box_mic

speaker:
  - platform: esp_adf
    id: box_speaker

voice_assistant:
  id: va
  microphone: box_mic
  speaker: box_speaker
  use_wake_word: true
  noise_suppression_level: 2
  auto_gain: 31dBFS
  volume_multiplier: 2.0
  vad_threshold: 3
  on_listening:
    - display.page.show: listening_page
    - component.update: s3_box_lcd
  on_tts_start:
    - display.page.show: talking_page
    - component.update: s3_box_lcd
  on_end:
    - delay: 100ms
    - wait_until:
        not:
          speaker.is_playing:
    - script.execute: reset_display
  on_stt_vad_end:
    - display.page.show: thinking_page
    - component.update: s3_box_lcd
  on_error:
    - display.page.show: error_page
    - component.update: s3_box_lcd
    - delay: 1s
    - script.execute: reset_display
  on_client_connected:
    - if:
        condition:
          switch.is_on: use_wake_word
        then:
          - voice_assistant.start_continuous:
          - script.execute: reset_display
  on_client_disconnected:
    - if:
        condition:
          switch.is_on: use_wake_word
        then:
          - voice_assistant.stop:
          - display.page.show: sleeping_page
          - component.update: s3_box_lcd

script:
  - id: reset_display
    then:
      - if:
          condition:
            wifi.connected:
          then:
            - if:
                condition:
                  api.connected:
                then:
                  - if:
                      condition:
                        switch.is_on: use_wake_word
                      then:
                        - display.page.show: idle_page
                        - component.update: s3_box_lcd
                      else:
                        - display.page.show: vad_off_page
                        - component.update: s3_box_lcd
                else:
                  - display.page.show: no_api_page
                  - component.update: s3_box_lcd
          else:
            - display.page.show: no_wifi_page
            - component.update: s3_box_lcd

switch:
  - platform: template
    name: Use wake word
    id: use_wake_word
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config
    on_turn_on:
      - lambda: id(va).set_use_wake_word(true);
      - if:
          condition:
            not:
              - voice_assistant.is_running
          then:
            - voice_assistant.start_continuous
      - script.execute: reset_display
    on_turn_off:
      - voice_assistant.stop
      - lambda: id(va).set_use_wake_word(false);
      - script.execute: reset_display

image:
  - file: https://github.com/esphome/firmware/raw/main/voice-assistant/casita/Upset@2x.png
    id: casita_error
    resize: 200x200
    type: RGB24
    use_transparency: true
  - file: https://github.com/esphome/firmware/raw/main/voice-assistant/casita/Sleeping@2x.png
    id: casita_idle
    resize: 200x200
    type: RGB24
    use_transparency: true
  - file: https://github.com/esphome/firmware/raw/main/voice-assistant/casita/Happy@2x.png
    id: casita_listening
    resize: 200x200
    type: RGB24
    use_transparency: true
  - file: https://github.com/esphome/firmware/raw/main/voice-assistant/casita/Initializing@2x.png
    id: casita_no_api
    resize: 200x200
    type: RGB24
    use_transparency: true
  - file: https://github.com/esphome/firmware/raw/main/voice-assistant/casita/NoInternet@2x.png
    id: casita_no_wifi
    resize: 200x200
    type: RGB24
    use_transparency: true
  - file: https://github.com/esphome/firmware/raw/main/voice-assistant/casita/Sleeping@2x.png
    id: casita_sleeping
    resize: 200x200
    type: RGB24
    use_transparency: true
  - file: https://github.com/esphome/firmware/raw/main/voice-assistant/casita/Grinning@2x.png
    id: casita_talking
    resize: 200x200
    type: RGB24
    use_transparency: true
  - file: https://github.com/esphome/firmware/raw/main/voice-assistant/casita/Focusing@2x.png
    id: casita_thinking
    resize: 200x200
    type: RGB24
    use_transparency: true
  - file: https://github.com/esphome/firmware/raw/main/voice-assistant/casita/Sleeping@2x.png
    id: casita_vad_off
    resize: 200x200
    type: RGB24
    use_transparency: true

spi:
  clk_pin: 7
  mosi_pin: 6

display:
  - platform: ili9xxx
    id: s3_box_lcd
    model: S3BOX
    data_rate: 40MHz
    cs_pin: 5
    dc_pin: 4
    reset_pin: 48
    update_interval: never
    pages:
      - id: error_page
        lambda: |-
          it.fill(Color::WHITE);
          it.image((it.get_width() / 2) - 100, (it.get_height() / 2) - 100, id(casita_error));
      - id: idle_page
        lambda: |-
          it.fill(Color::WHITE);
          it.image((it.get_width() / 2) - 100, (it.get_height() / 2) - 100, id(casita_idle));
      - id: listening_page
        lambda: |-
          it.fill(Color::WHITE);
          it.image((it.get_width() / 2) - 100, (it.get_height() / 2) - 100, id(casita_listening));
      - id: no_api_page
        lambda: |-
          it.fill(Color::BLACK);
          it.image((it.get_width() / 2) - 100, (it.get_height() / 2) - 100, id(casita_no_api));
      - id: no_wifi_page
        lambda: |-
          it.fill(Color::BLACK);
          it.image((it.get_width() / 2) - 100, (it.get_height() / 2) - 100, id(casita_no_wifi));
      - id: sleeping_page
        lambda: |-
          it.fill(Color::WHITE);
          it.image((it.get_width() / 2) - 100, (it.get_height() / 2) - 100, id(casita_sleeping));
      - id: talking_page
        lambda: |-
          it.fill(Color::WHITE);
          it.image((it.get_width() / 2) - 100, (it.get_height() / 2) - 100, id(casita_talking));
      - id: thinking_page
        lambda: |-
          it.fill(Color::WHITE);
          it.image((it.get_width() / 2) - 100, (it.get_height() / 2) - 105, id(casita_thinking));
      - id: vad_off_page
        lambda: |-
          it.fill(Color::BLACK);
          it.image((it.get_width() / 2) - 100, (it.get_height() / 2) - 100, id(casita_vad_off));
