substitutions:
  name: "m5stack-atom-echo"
  friendly_name: "M5Stack Atom Echo"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: m5stack.atom-echo-voice-assistant
    version: "1.0"

esp32:
  board: m5stack-atom
  framework:
    type: arduino

logger:
api:
ota:

dashboard_import:
  package_import_url: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main

wifi:
  ap:
    password: "${wifi_ap_password}"

captive_portal:

improv_serial:

i2s_audio:
  i2s_lrclk_pin: GPIO33
  i2s_bclk_pin: GPIO19

microphone:
  - platform: i2s_audio
    id: echo_microphone
    i2s_din_pin: GPIO23

media_player:
  - platform: i2s_audio
    name: None
    id: echo_audio
    dac_type: external
    i2s_dout_pin: GPIO22
    mode: mono

voice_assistant:
  microphone: echo_microphone

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: Button
    id: echo_button
    on_press:
      - light.turn_on:
          id: led
          blue: 100%
      - voice_assistant.start:
    on_release:
      - light.turn_off: led
      - voice_assistant.stop:

light:
  - platform: fastled_clockless
    id: led
    name: None
    pin: GPIO27
    chipset: SK6812
    num_leds: 1
    rgb_order: grb
