substitutions:
  name: esphome-web

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  project:
    name: esphome.web
    version: "1.0"

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point
  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/firmware/esphome-web/esp32s2.yaml@v2
  import_full_config: true

# To have a "next url" for improv serial
web_server:
