esphome:
  name: esphome-web
  friendly_name: ESPHome Web
  min_version: 2024.11.0
  name_add_mac_suffix: true

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  - platform: esphome

wifi:
