name: Build ESPHome Web

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'esphome-web/**'
      - '.github/workflows/build-esphome-web.yml'
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-firmware:
    name: Build ESPHome Web Firmware
    uses: esphome/workflows/.github/workflows/build.yml@main
    with:
      files: |
        esphome-web/esp32.yaml
        esphome-web/esp32c3.yaml
        esphome-web/esp32s2.yaml
        esphome-web/esp32s3.yaml
        esphome-web/esp8266.yaml
        esphome-web/pico-w.yaml
      esphome-version: 2024.7.3
      combined-name: esphome-web
      release-summary: ${{ github.event_name == 'release' && github.event.release.body || '' }}
      release-url: ${{ github.event_name == 'release' && github.event.release.url || '' }}
      release-version: ${{ github.event_name == 'release' && github.event.release.tag_name || '' }}

  upload:
    if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')
    name: Upload to R2
    needs:
      - build-firmware
    uses: esphome/workflows/.github/workflows/upload.yml@main
    with:
      name: esphome-web
      version: ${{ needs.build-firmware.outputs.version }}
    secrets: inherit
